### ISSUE TITLE
Remove whitelist from module name

### ISSUE THREAD

**Issue by wilburec** [backdrop-contrib/login_whitelist#1]
Following Backdrop's decision to remove the terms whitelist and blacklist from core, we should also follow suite and change the name of this module.  

Can do?

**Comment by findlabnet** [comment]
Need found/select technically correct way for upgrade path (and spare time) to do it.

**Comment by findlabnet** [comment]
This module is the same as its renamed successor, the "Login allowlist" module available at https://backdropcms.org/project/login_allowlist or https://github.com/backdrop-contrib/login_allowlist, which was created with the goal of inclusive naming. Any future changes will be synchronized.
